### PR TITLE
[Fix]: Fixed issue with scipy on running gunicorn server inside a docker container.

### PR DESCRIPTION
**Pull request by avas27JTG**
## Description
`scipy>=1.4.1` is not working on running the gunicorn server inside a docker container and it gives below error

```
(base) mambauser@f8c994d6c08f:/opt/chemprop/chemprop/web$ gunicorn --bind 0.0.0.0:5000 "wsgi:build_app(init_db=True, root_folder='/opt/chemprop/data')"
[2023-07-31 08:08:46 +0000] [24] [INFO] Starting gunicorn 21.2.0
[2023-07-31 08:08:46 +0000] [24] [INFO] Listening at: http://0.0.0.0:5000 (24)
[2023-07-31 08:08:46 +0000] [24] [INFO] Using worker: sync
[2023-07-31 08:08:46 +0000] [25] [INFO] Booting worker with pid: 25
Unable to make new descriptors, descriptor generator requirements not properly installed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/descriptastorus/DescriptaStore.py", line 42, in <module>
    from .descriptors import MakeGenerator
  File "/opt/conda/lib/python3.11/site-packages/descriptastorus/descriptors/__init__.py", line 3, in <module>
    from .rdNormalizedDescriptors import *
  File "/opt/conda/lib/python3.11/site-packages/descriptastorus/descriptors/rdNormalizedDescriptors.py", line 49, in <module>
    dist = getattr(st, dist)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'scipy.stats' has no attribute 'gilbrat'
[2023-07-31 08:08:48 +0000] [25] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/chemprop/chemprop/web/wsgi.py", line 5, in <module>
    from chemprop.web.app import app, db
  File "/opt/chemprop/chemprop/__init__.py", line 1, in <module>
    import chemprop.data
  File "/opt/chemprop/chemprop/data/__init__.py", line 1, in <module>
    from .data import cache_graph, cache_mol, MoleculeDatapoint, MoleculeDataset, MoleculeDataLoader, \
  File "/opt/chemprop/chemprop/data/data.py", line 11, in <module>
    from chemprop.features import get_features_generator
  File "/opt/chemprop/chemprop/features/__init__.py", line 1, in <module>
    from .features_generators import get_available_features_generators, get_features_generator, \
  File "/opt/chemprop/chemprop/features/features_generators.py", line 93, in <module>
    from descriptastorus.descriptors import rdDescriptors, rdNormalizedDescriptors
  File "/opt/conda/lib/python3.11/site-packages/descriptastorus/descriptors/__init__.py", line 3, in <module>
    from .rdNormalizedDescriptors import *
  File "/opt/conda/lib/python3.11/site-packages/descriptastorus/descriptors/rdNormalizedDescriptors.py", line 49, in <module>
    dist = getattr(st, dist)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'scipy.stats' has no attribute 'gilbrat'
[2023-07-31 08:08:48 +0000] [25] [INFO] Worker exiting (pid: 25)
[2023-07-31 08:08:48 +0000] [24] [ERROR] Worker (pid:25) exited with code 3
[2023-07-31 08:08:48 +0000] [24] [ERROR] Shutting down: Master
[2023-07-31 08:08:48 +0000] [24] [ERROR] Reason: Worker failed to boot.
```

changing `scipy>=1.4.1` to `scipy>=1.9.0` in the file `environment.yml` resolves the issue.

Fix for the issue https://github.com/chemprop/chemprop/issues/435

### CODE REVIEW

**Review by kevingreenman — CHANGES_REQUESTED** [review]
Hi @avas27JTG, thanks for the PR! Please see the discussion in #429 and #431 about why we chose to use conditional dependencies rather than change the scipy version to 1.9.0 and modify your PR accordingly.

**Comment by JacksonBurns** [comment]
Ah, we missed the `environment.yml` file in #431. The change in this PR will not work with Python 3.7 (scipy 1.9 is only compatible with 3.8 or newer) and it is not possible to have conditional dependencies in the conda environment specification like we did in #431. There would need to be a separate `environment.yml` for Python 3.7 and 3.8

**Comment by kevingreenman** [comment]
@JacksonBurns thanks for the input. Is the same true of `setup.cfg`? I see that was also changed in #429 but not #431. 
Would having more than one `environment.yml` (and/or `setup.cfg`) file cause issues?

**Comment by JacksonBurns** [comment]
Yes we also did not update `setup.cfg`, but all that file does is provide default options for `setup.py` so in specifying the deps there we were fine. We don't strictly have to update it, though it would probably be nice for clarity. Not sure how to add conditional dependencies there.

Having multiple conda environment files should not cause any problems, afaik.

**Comment by KnathanM** [comment]
@avas27JTG Does the solution below work for you? If you check the box on GitHub to allow maintainers to edit your PR, I am happy to implement these changes for you to test. 

The required changes are in `chemprop/Dockerfile`. 
Change line 13 
`RUN micromamba install -y -n base -f /tmp/environment.yml && \`

to
`RUN micromamba install -y -n base python=3.8 && \`

(You can also delete line 11 that copies the `environment.yml` file while you're at it.)

In discussion with @JacksonBurns, we found the dependencies listed in the `setup.py` file are installed with `RUN /opt/conda/bin/python -m pip install -e .`. Installing them first from the `environment.yml` file is redundant and less flexible. 

The solution above forces docker users to use python 3.8, but still allows non docker users to use python 3.7 or 3.8. If there are docker users who want python 3.7, we would need to find another solution, perhaps having two `environment.yml` files. 

As a note to the other developers, this is also relevant in how we recommend to install chemprop from source. Our current recommendation in `README.md` is 

1. `git clone https://github.com/chemprop/chemprop.git`
2. `cd chemprop`
3. `conda env create -f environment.yml`
4. `conda activate chemprop`
5. `pip install -e .`

This doesn't utilize the conditional dependencies in the `setup.py` file. Perhaps we should open another PR to specify the `environment.yml` only works for a specific python version (we could choose either 3.7 or 3.8) and say the recommend source installation is

1. `git clone https://github.com/chemprop/chemprop.git`
2. `cd chemprop`
3. `conda create -n chemprop python=<3.7|3.8>`
4. `conda activate chemprop`
5. `pip install -e .`

What do you think @kevingreenman ?

**Comment by avas27JTG** [comment]
@KnathanM I'm not available for some time, so I won't be able to test or look into it. Please feel free to make changes to my PR in a separate branch as I don't have access to enable the settings as of now.

**Comment by KnathanM** [comment]
After reviewing the issue history again, I'm a bit confused. It looks like we didn't need to do anything when `gilbrat` was changed to `gibrat`, our `setup.py` file could have been unchanged, and users just needed to update their version of `descriptastorus`. @kevingreenman @shihchengli Can you check my understanding below?

In #428, it was claimed that "`descriptastorus` requires scipy>=1.9.0", which is a problem since `scipy>=1.8.0` doesn't support python 3.7. But when I look at the [descriptastorus](https://github.com/bp-kelley/descriptastorus) website, their `requirements.txt` includes `scipy>=1.7.0`. 

In this PR, the error is in [descriptastorus/descriptors/rdNormalizedDescriptors.py](https://github.com/bp-kelley/descriptastorus/tree/da9760932ab9a78b116bc697795dd9e1798f087a/descriptastorus/descriptors/rdNormalizedDescriptors.py), where it tries to get the `gilbrat` attribute from `scipy.stats`: `dist = getattr(st, dist)`, which means @avas27JTG is using a version of `scipy>=1.11`. That should be fine if the most recent version of `descriptastorus` is used. It adds this block of code that makes it compatible with any version of `scipy`. 

``` if dist in ['gilbrat', 'gibrat']:
        # fix change in scikit learn
        if hasattr(dist, 'gilbrat'):
            dist = 'gilbrat'
        else:
            dist = 'gibrat'
```
Perhaps we should catch the `AttributeError: module 'scipy.stats' has no attribute 'gilbrat'` and tell users more helpfully that they need to update `descriptastorus`. I'll open a PR.

**Comment by shihchengli** [comment]
Hi @KnathanM, thanks for taking some time on this issue. You're right to say that descriptastorus requires SciPy>=1.7.0 rather than 1.9.0 – my bad for the typo in issue #428. It seems using an older version of descriptastorus with SciPy>=1.11.0 could cause the errors shown here. It is interesting that specifying SciPy>=1.9.0 can solve the problem. I guess either this setting installs an older SciPy version which still supports the `gilbrat` distribution or installs a newer version of descriptastorus. It would be helpful if @avas27JTG  could check the exact versions of SciPy and descriptastorus installed with scipy>=1.4.1 and scipy>=1.9.0.

For users with an older descriptastorus version, installing SciPy<1.11.0 seems necessary. However, for those with a newer descriptastorus version >=2.6.1, the issue is supposed to be resolved by the code block you mentioned.

It seems there is a potential bug in their PR for version fix. Regarding the code of `hasattr(dist, 'gilbrat')`, I think it should be replaced with `hasattr(st, 'gilbrat')`. The hasattr() function checks if an object has a specified attribute, returning True if it does and False otherwise. If I understand correctly, `dist` appears to be a string, and `hasattr(dist, 'gilbrat')` would always return False, leading to the incorrect assignment of `gibrat` as the distribution. This error might be the cause of the issues I faced before, rather than a version conflict.

**Comment by KnathanM** [comment]
I think you are correct that the issue is `hasattr(dist, 'gilbrat')` should be `hasattr(st, 'gilbrat')` in descriptastorus. I've opened that issue on the descriptastorus repo and hopefully they fix it. Until then it looks like we have to require scipy>1.9 if descriptastorus 2.6.1 is used. 

This also answers why scipy 1.9.0 fixes the issue in this PR as that version was the first to have `gibrat`. descriptastorus 2.6.1 always tries to get the gibrat attribute from scipy.stats which will fail for any scipy<1.9.
