### ISSUE TITLE
[v2 BUG]: ImportError when trying to run tutorial notebook on Google Colab

### ISSUE THREAD

**Issue by nadeennassif** [chemprop/chemprop#871]
**Describe the bug**
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-36-0e17cbdac1bc>](https://localhost:8080/#) in <cell line: 2>()
      1 from chemprop import data
----> 2 from chemprop import featurizers, models, nn

ImportError: cannot import name 'featurizers' from 'chemprop' (/usr/local/lib/python3.10/dist-packages/chemprop/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
**Example(s)**
from chemprop import data, featurizers, models, nn
```

**Additional context**
![Uploading Untitled22.ipynb - Colab - Google Chrome 17_05_2024 20_46_05.png…]()

**Comment by kevingreenman** [comment]
@nadeennassif I'm not able to see your screenshot. Are you trying to run the example notebook using Google Colab? The notebooks are meant to be run locally after installing the chemprop environment. If you'd like to run the notebook in colab, you'll have to add a cell to the top of the notebook to install all the dependencies.

**Comment by kevingreenman** [comment]
To run a notebook locally, install the chemprop environment using the instructions [here](https://chemprop.readthedocs.io/en/main/installation.html#option-2-installing-from-source-using-pip), except replacing the last line with `pip install -e ".[notebooks]" to get the extra `ipykernels` dependency that the notebooks require.

**Comment by nadeennassif** [comment]
---------------------------------------------------------------------------


ImportError                               Traceback (most recent call last)


<ipython-input-10-0e50905cb523><https://localhost:8080/#> in <cell line: 1>()
----> 1 from chemprop import data, featurizers, models, nn



ImportError: cannot import name 'featurizers' from 'chemprop' (/usr/local/lib/python3.10/dist-packages/chemprop/__init__.py)

This is the error
in from chemprop import data, featurizers, nn
________________________________

**Comment by kevingreenman** [comment]
@nadeennassif that looks like the same error from your first post. Did you try my suggestion for installing the environment?

**Comment by nadeennassif** [comment]
Yes the 2nd version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kevingreenman** [comment]
I'm sorry, I don't understand. Please elaborate on which commands you ran to install your environment. Please also specify which notebook you're trying to run.

**Comment by nadeennassif** [comment]
I’m tryig to run training notebook in version 2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nadeennassif** [comment]
this notebook
https://chemprop.readthedocs.io/en/main/training.html
I'm in the first cell
________________________________

**Comment by kevingreenman** [comment]
again, please elaborate on which commands you ran to install your environment before trying to run the notebook

**Comment by nadeennassif** [comment]
I'm just working with python version Python Python 3.12.3
I'm working on google colab
here's all the installations
# Download the Miniconda installer
!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# Make the installer executable
!chmod +x Miniconda3-latest-Linux-x86_64.sh

# Install Miniconda
!bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local

# Initialize conda
!conda init

# Reload the bash configuration
!source ~/.bashrc


!git clone https://github.com/chemprop/chemprop.git
!cd /content/chemprop
!conda env create -f /content/chemprop/environment.yml
!conda activate chemprop
 and I've installed all the versions required in .yml file


________________________________

**Comment by kevingreenman** [comment]
@nadeennassif we don't currently support running our notebooks on Google Colab but are working on providing this option. In the meantime, you can follow our instructions for installing the chemprop environment locally on your machine and run the notebooks that way.
